import { CLAUDE_MODEL_WEIGHTS, CODEX_MODEL_WEIGHTS } from './model-weights.js';

export const SUBSCRIPTION_PRESETS = {
  'chatgpt-plus': {
    label: 'ChatGPT Plus',
    upstream: 'codex',
    credits: 100,
    windowMs: 5 * 3600_000,
    weeklyCredits: 500,
    weeklyWindowMs: 7 * 24 * 3600_000,
    modelWeights: CODEX_MODEL_WEIGHTS,
    defaultWeight: 1.0,
  },
  'chatgpt-pro': {
    label: 'ChatGPT Pro',
    upstream: 'codex',
    credits: 500,
    windowMs: 5 * 3600_000,
    weeklyCredits: 2_500,
    weeklyWindowMs: 7 * 24 * 3600_000,
    modelWeights: CODEX_MODEL_WEIGHTS,
    defaultWeight: 1.0,
  },
  'chatgpt-business': {
    label: 'ChatGPT Business',
    upstream: 'codex',
    credits: 700,
    windowMs: 5 * 3600_000,
    weeklyCredits: 3_500,
    weeklyWindowMs: 7 * 24 * 3600_000,
    modelWeights: CODEX_MODEL_WEIGHTS,
    defaultWeight: 1.0,
  },
  'chatgpt-enterprise': {
    label: 'ChatGPT Enterprise',
    upstream: 'codex',
    credits: 1_500,
    windowMs: 5 * 3600_000,
    weeklyCredits: 7_500,
    weeklyWindowMs: 7 * 24 * 3600_000,
    modelWeights: CODEX_MODEL_WEIGHTS,
    defaultWeight: 1.0,
  },
  'claude-pro': {
    label: 'Claude Pro',
    upstream: 'claude',
    credits: 45,
    windowMs: 5 * 3600_000,
    weeklyCredits: 315,
    weeklyWindowMs: 7 * 24 * 3600_000,
    modelWeights: CLAUDE_MODEL_WEIGHTS,
    defaultWeight: 1.0,
  },
  'claude-max-5x': {
    label: 'Claude Max 5×',
    upstream: 'claude',
    credits: 225,
    windowMs: 5 * 3600_000,
    weeklyCredits: 1_575,
    weeklyWindowMs: 7 * 24 * 3600_000,
    modelWeights: CLAUDE_MODEL_WEIGHTS,
    defaultWeight: 1.0,
  },
  'claude-max-20x': {
    label: 'Claude Max 20×',
    upstream: 'claude',
    credits: 900,
    windowMs: 5 * 3600_000,
    weeklyCredits: 6_300,
    weeklyWindowMs: 7 * 24 * 3600_000,
    modelWeights: CLAUDE_MODEL_WEIGHTS,
    defaultWeight: 1.0,
  },
  'gemini-free': {
    label: 'Gemini Free',
    upstream: 'gemini',
    credits: 100,
    windowMs: 24 * 3600_000,
    modelWeights: {},
    defaultWeight: 1.0,
  },
  'gemini-standard': {
    label: 'Gemini Advanced',
    upstream: 'gemini',
    credits: 1_000,
    windowMs: 24 * 3600_000,
    modelWeights: {},
    defaultWeight: 1.0,
  },
  'gemini-paid': {
    label: 'Gemini Paid',
    upstream: 'gemini',
    credits: 2_000,
    windowMs: 24 * 3600_000,
    modelWeights: {},
    defaultWeight: 1.0,
  },
  custom: {
    label: 'Custom',
    upstream: 'any',
    credits: 0,
    windowMs: 3600_000,
    modelWeights: {},
    defaultWeight: 1.0,
  },
} as const;

export type SubscriptionTier = keyof typeof SUBSCRIPTION_PRESETS;
